---
name: Lint Code Base
on:
  push:
    branches: [main]
  pull_request:
    branches: '**'
  workflow_dispatch: {}

permissions:
  contents: read
  statuses: write

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Essential for detecting changed files
      - name: Lint Code Base
        uses: github/super-linter@61abc07d755095a68f4987d1c2c3d1d64408f1f9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false # Only lint changed files
          DEFAULT_BRANCH: main
