---
name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@c0e2f3e4c8e9c8a0b8f2c7a6b5e4d3f2a1b0c9d8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
